"""Protocol catalogue for the Learning Network module.

Each category groups protocols following the 30 sections requested.
Every protocol entry has:
    name        - protocol name (kept as-is, mostly universal acronyms)
    desc        - dict with short technical description per language (en/pt), ru falls back to en
    builder     - optional key into scapy_demos.BUILDERS for a real crafted-packet demo
If `builder` is None, the menu falls back to a generic conceptual animated
explanation (still an "example" per protocol, without requiring hardware or
a dedicated Scapy layer).
"""

def P(name, en, pt=None, builder=None, layer=""):
    return {
        "name": name,
        "layer": layer,
        "desc": {"en": en, "pt": pt or en},
        "builder": builder,
    }


CATEGORIES = [
    {
        "id": "l1",
        "title": {"en": "1. Physical Layer (L1)", "pt": "1. Camada Física (L1)", "ru": "1. Физический уровень (L1)"},
        "protocols": [
            P("Ethernet", "Base wired LAN standard", "Padrão básico de rede local cabeada"),
            P("IEEE 802.3", "Ethernet standard family", "Família de padrões Ethernet"),
            P("100BASE-TX", "100 Mbps over copper twisted pair", "100 Mbps em par trançado de cobre"),
            P("1000BASE-T", "1 Gbps over copper (Cat5e+)", "1 Gbps em cobre (Cat5e+)"),
            P("2.5GBASE-T", "2.5 Gbps over copper", "2.5 Gbps em cobre"),
            P("5GBASE-T", "5 Gbps over copper", "5 Gbps em cobre"),
            P("10GBASE-T", "10 Gbps over copper (Cat6a+)", "10 Gbps em cobre (Cat6a+)"),
            P("25GbE", "25 Gigabit Ethernet", "Ethernet de 25 Gigabit"),
            P("40GbE", "40 Gigabit Ethernet", "Ethernet de 40 Gigabit"),
            P("100GbE", "100 Gigabit Ethernet", "Ethernet de 100 Gigabit"),
            P("200GbE", "200 Gigabit Ethernet", "Ethernet de 200 Gigabit"),
            P("400GbE", "400 Gigabit Ethernet", "Ethernet de 400 Gigabit"),
            P("800GbE", "800 Gigabit Ethernet", "Ethernet de 800 Gigabit"),
            P("1000BASE-SX/LX", "Gigabit fiber (short/long reach)", "Fibra Gigabit (curto/longo alcance)"),
            P("10GBASE-SR/LR", "10G fiber (short/long reach)", "Fibra 10G (curto/longo alcance)"),
            P("25GBASE-SR/LR", "25G fiber", "Fibra 25G"),
            P("40GBASE-SR4/LR4", "40G fiber (parallel/WDM)", "Fibra 40G (paralela/WDM)"),
            P("100GBASE-SR4/LR4", "100G fiber (parallel/WDM)", "Fibra 100G (paralela/WDM)"),
            P("PON", "Passive Optical Network (shared fiber access)", "Rede óptica passiva (acesso em fibra compartilhado)"),
            P("GPON", "Gigabit PON, common in FTTH", "PON Gigabit, comum em FTTH"),
            P("XG-PON", "10G downstream PON", "PON com 10G downstream"),
            P("XGS-PON", "Symmetric 10G PON", "PON simétrica de 10G"),
            P("EPON", "Ethernet PON", "PON baseada em Ethernet"),
            P("IEEE 802.11a", "5GHz Wi-Fi, up to 54 Mbps", "Wi-Fi 5GHz, até 54 Mbps"),
            P("802.11b", "2.4GHz Wi-Fi, up to 11 Mbps", "Wi-Fi 2.4GHz, até 11 Mbps"),
            P("802.11g", "2.4GHz Wi-Fi, up to 54 Mbps", "Wi-Fi 2.4GHz, até 54 Mbps"),
            P("802.11n", "Wi-Fi 4, MIMO, up to 600 Mbps", "Wi-Fi 4, MIMO, até 600 Mbps"),
            P("802.11ac", "Wi-Fi 5, wider channels, MU-MIMO", "Wi-Fi 5, canais maiores, MU-MIMO"),
            P("802.11ax (Wi-Fi 6/6E)", "OFDMA, better efficiency, 6GHz band (6E)", "OFDMA, mais eficiência, banda 6GHz (6E)"),
            P("802.11be (Wi-Fi 7)", "Multi-link operation, up to 46 Gbps", "Operação multi-link, até 46 Gbps"),
            P("GSM", "2G cellular voice/SMS", "Celular 2G voz/SMS"),
            P("GPRS", "2.5G packet data over GSM", "Dados em pacote 2.5G sobre GSM"),
            P("EDGE", "Enhanced 2.75G data rates", "Taxas de dados 2.75G aprimoradas"),
            P("UMTS", "3G cellular (WCDMA)", "Celular 3G (WCDMA)"),
            P("HSPA", "3.5G high-speed packet access", "Acesso de pacote de alta velocidade 3.5G"),
            P("LTE", "4G cellular, all-IP", "Celular 4G, totalmente IP"),
            P("LTE-Advanced", "Enhanced 4G (carrier aggregation)", "4G aprimorado (agregação de portadoras)"),
            P("5G NR", "5G New Radio", "Nova rádio 5G"),
        ],
    },
    {
        "id": "l2",
        "title": {"en": "2. Data Link Layer (L2)", "pt": "2. Camada de Enlace (L2)", "ru": "2. Канальный уровень (L2)"},
        "protocols": [
            P("Ethernet", "Frames addressed by MAC", "Quadros endereçados por MAC", builder="ethernet_arp"),
            P("IEEE 802.3", "Ethernet frame format standard", "Padrão de formato de quadro Ethernet"),
            P("IEEE 802.1Q (VLAN)", "Adds a VLAN tag to Ethernet frames", "Adiciona tag de VLAN aos quadros Ethernet", builder="vlan"),
            P("STP (802.1D)", "Prevents L2 loops via a spanning tree", "Evita loops L2 via árvore de span", builder="stp"),
            P("RSTP (802.1w)", "Rapid convergence version of STP", "Versão de convergência rápida do STP"),
            P("MSTP (802.1s)", "Multiple spanning trees per VLAN group", "Múltiplas árvores por grupo de VLAN"),
            P("LACP (802.1AX)", "Bundles links into one logical link", "Agrupa links em um link lógico"),
            P("802.1X", "Port-based network access control", "Controle de acesso à rede baseado em porta", builder="eapol"),
            P("EAP", "Extensible Authentication Protocol framework", "Framework de autenticação extensível"),
            P("EAPOL", "EAP encapsulated over LAN", "EAP encapsulado sobre LAN", builder="eapol"),
            P("LLDP", "Vendor-neutral neighbor discovery", "Descoberta de vizinhos neutra de fabricante", builder="lldp"),
            P("CDP", "Cisco neighbor discovery protocol", "Protocolo de descoberta de vizinhos da Cisco"),
            P("PPP", "Point-to-Point Protocol for serial links", "Protocolo ponto a ponto para links seriais", builder="pppoe"),
            P("PPPoE", "PPP sessions over Ethernet (common in DSL)", "Sessões PPP sobre Ethernet (comum em DSL)", builder="pppoe"),
            P("LCP", "PPP Link Control Protocol", "Protocolo de controle de link do PPP"),
            P("NCP", "PPP Network Control Protocol", "Protocolo de controle de rede do PPP"),
            P("ARP", "Resolves IPv4 address to MAC address", "Resolve endereço IPv4 para MAC", builder="ethernet_arp"),
            P("RARP", "Resolves MAC to IPv4 (legacy)", "Resolve MAC para IPv4 (legado)"),
        ],
    },
    {
        "id": "l3",
        "title": {"en": "3. Network Layer (L3)", "pt": "3. Camada de Rede (L3)", "ru": "3. Сетевой уровень (L3)"},
        "protocols": [
            P("IPv4", "32-bit addressing, the classic Internet Protocol", "Endereçamento de 32 bits, o IP clássico", builder="ipv4_icmp"),
            P("IPv6", "128-bit addressing, successor to IPv4", "Endereçamento de 128 bits, sucessor do IPv4", builder="ipv6_icmpv6"),
            P("ICMP", "Control/diagnostic messages for IPv4 (ping, errors)", "Mensagens de controle/diagnóstico IPv4 (ping, erros)", builder="ipv4_icmp"),
            P("ICMPv6", "Control/diagnostic messages for IPv6 (+ NDP)", "Mensagens de controle/diagnóstico IPv6 (+ NDP)", builder="ipv6_icmpv6"),
            P("IGMP", "Manages multicast group membership", "Gerencia associação a grupos multicast", builder="igmp"),
            P("NDP", "IPv6 neighbor discovery (replaces ARP)", "Descoberta de vizinhos IPv6 (substitui ARP)"),
            P("MLD", "IPv6 multicast listener discovery", "Descoberta de ouvintes multicast IPv6"),
            P("ping (ICMP echo)", "Round-trip reachability test", "Teste de alcançabilidade ida-e-volta", builder="ipv4_icmp"),
            P("traceroute", "Maps the path to a destination via TTL expiry", "Mapeia o caminho via expiração de TTL", builder="traceroute"),
            P("ICMP Destination Unreachable", "Signals the packet could not be delivered", "Sinaliza que o pacote não pôde ser entregue"),
            P("ICMP Time Exceeded", "Signals TTL reached zero in transit", "Sinaliza que o TTL chegou a zero em trânsito", builder="traceroute"),
        ],
    },
    {
        "id": "routing",
        "title": {"en": "4. Routing Protocols", "pt": "4. Protocolos de Roteamento", "ru": "4. Протоколы маршрутизации"},
        "protocols": [
            P("RIPv1", "Distance-vector routing, no subnet mask", "Roteamento vetor-distância, sem máscara"),
            P("RIPv2", "Distance-vector routing with subnet masks", "Vetor-distância com máscara de sub-rede"),
            P("RIPng", "RIP for IPv6", "RIP para IPv6"),
            P("OSPFv2", "Link-state IGP for IPv4", "IGP de estado de enlace para IPv4", builder="ospf"),
            P("OSPFv3", "Link-state IGP for IPv6", "IGP de estado de enlace para IPv6", builder="ospf"),
            P("IS-IS", "Link-state IGP, common in ISP cores", "IGP de estado de enlace, comum em núcleos de ISP"),
            P("EIGRP", "Cisco advanced distance-vector IGP", "IGP vetor-distância avançado da Cisco"),
            P("BGP-4", "Path-vector protocol between Autonomous Systems", "Protocolo vetor-caminho entre Sistemas Autônomos", builder="bgp"),
            P("MP-BGP", "BGP extension for multiple address families", "Extensão BGP para múltiplas famílias de endereço", builder="bgp"),
        ],
    },
    {
        "id": "l4",
        "title": {"en": "5. Transport Layer (L4)", "pt": "5. Camada de Transporte (L4)", "ru": "5. Транспортный уровень (L4)"},
        "protocols": [
            P("TCP", "Connection-oriented, reliable, ordered delivery", "Orientado a conexão, confiável, ordenado", builder="tcp_handshake"),
            P("UDP", "Connectionless, minimal overhead", "Sem conexão, overhead mínimo", builder="udp_dns"),
            P("SCTP", "Message-oriented, multi-streaming transport", "Transporte orientado a mensagens, multi-stream"),
            P("DCCP", "Datagram transport with congestion control", "Transporte de datagramas com controle de congestionamento"),
        ],
    },
    {
        "id": "quic",
        "title": {"en": "6. QUIC", "pt": "6. QUIC", "ru": "6. QUIC"},
        "protocols": [
            P("QUIC", "Reliable transport over UDP, used by HTTP/3", "Transporte confiável sobre UDP, usado pelo HTTP/3"),
        ],
    },
    {
        "id": "security",
        "title": {"en": "7. Security", "pt": "7. Segurança", "ru": "7. Безопасность"},
        "protocols": [
            P("TLS 1.2", "Encrypted transport handshake + record protocol", "Handshake de transporte criptografado", builder="tls"),
            P("TLS 1.3", "Faster, more secure TLS handshake (1-RTT)", "Handshake TLS mais rápido e seguro (1-RTT)", builder="tls"),
            P("SSL 2.0", "Obsolete, insecure, deprecated", "Obsoleto, inseguro, descontinuado"),
            P("SSL 3.0", "Obsolete, insecure, deprecated", "Obsoleto, inseguro, descontinuado"),
            P("AH", "IPsec Authentication Header (integrity, no encryption)", "Cabeçalho de autenticação IPsec (integridade, sem cifra)"),
            P("ESP", "IPsec Encapsulating Security Payload (encryption)", "Carga de segurança encapsulada IPsec (cifra)"),
            P("IKE", "IPsec key exchange/negotiation", "Troca/negociação de chaves IPsec"),
            P("IKEv2", "Modern IPsec key exchange", "Troca de chaves IPsec moderna"),
            P("SSH", "Encrypted remote administration", "Administração remota criptografada"),
            P("OpenVPN", "SSL/TLS based VPN tunneling", "Tunelamento VPN baseado em SSL/TLS"),
            P("WireGuard", "Modern, minimal, fast VPN protocol", "Protocolo VPN moderno, minimalista e rápido"),
            P("L2TP", "Tunneling protocol, often paired with IPsec", "Protocolo de tunelamento, geralmente com IPsec"),
            P("PPTP", "Legacy VPN protocol, insecure", "Protocolo VPN legado, inseguro"),
            P("SSTP", "VPN tunneled over TLS/443", "VPN tunelada sobre TLS/443"),
        ],
    },
    {
        "id": "web",
        "title": {"en": "8. Application — Web", "pt": "8. Aplicação — Web", "ru": "8. Приложение — Web"},
        "protocols": [
            P("HTTP/1.0", "One request per connection", "Uma requisição por conexão", builder="http"),
            P("HTTP/1.1", "Persistent connections, pipelining", "Conexões persistentes, pipelining", builder="http"),
            P("HTTP/2", "Multiplexed streams over one TLS/TCP connection", "Streams multiplexados sobre uma conexão TLS/TCP", builder="http"),
            P("HTTP/3", "HTTP over QUIC/UDP", "HTTP sobre QUIC/UDP"),
            P("DNS", "Resolves names to IP addresses", "Resolve nomes para endereços IP", builder="udp_dns"),
            P("DoT", "DNS over TLS", "DNS sobre TLS"),
            P("DoH", "DNS over HTTPS", "DNS sobre HTTPS"),
            P("DoQ", "DNS over QUIC", "DNS sobre QUIC"),
            P("DNS A/AAAA record", "Maps a name to IPv4/IPv6", "Mapeia um nome para IPv4/IPv6", builder="udp_dns"),
            P("DNS CNAME/MX/NS/TXT/SOA/PTR/SRV/CAA/DNSKEY/DS", "Other common DNS record types", "Outros tipos comuns de registro DNS"),
        ],
    },
    {
        "id": "email",
        "title": {"en": "9. Email", "pt": "9. E-mail", "ru": "9. Электронная почта"},
        "protocols": [
            P("SMTP", "Sends/relays email between servers", "Envia/repassa e-mail entre servidores"),
            P("ESMTP", "Extended SMTP with capability negotiation", "SMTP estendido com negociação de capacidades"),
            P("SMTPS", "SMTP wrapped in TLS", "SMTP encapsulado em TLS"),
            P("POP3", "Downloads mail from a mailbox", "Baixa e-mails de uma caixa postal"),
            P("POP3S", "POP3 wrapped in TLS", "POP3 encapsulado em TLS"),
            P("IMAP", "Synchronizes mail state with the server", "Sincroniza o estado do e-mail com o servidor"),
            P("IMAPS", "IMAP wrapped in TLS", "IMAP encapsulado em TLS"),
            P("SPF", "Declares which hosts may send mail for a domain", "Declara quais hosts podem enviar e-mail pelo domínio"),
            P("DKIM", "Cryptographically signs outgoing mail", "Assina criptograficamente o e-mail enviado"),
            P("DMARC", "Policy combining SPF/DKIM results", "Política combinando resultados de SPF/DKIM"),
        ],
    },
    {
        "id": "files",
        "title": {"en": "10. File Transfer", "pt": "10. Transferência de Arquivos", "ru": "10. Передача файлов"},
        "protocols": [
            P("FTP", "Classic file transfer, separate control/data channels", "Transferência clássica, canais de controle/dados separados"),
            P("FTPS", "FTP wrapped in TLS", "FTP encapsulado em TLS"),
            P("SFTP", "File transfer over SSH (not FTP over TLS)", "Transferência sobre SSH (não é FTP sobre TLS)"),
            P("TFTP", "Trivial, connectionless file transfer over UDP", "Transferência trivial e sem conexão sobre UDP"),
            P("SCP", "Secure copy over SSH", "Cópia segura sobre SSH"),
            P("rsync", "Efficient incremental file synchronization", "Sincronização incremental eficiente de arquivos"),
        ],
    },
    {
        "id": "dhcp",
        "title": {"en": "11. DHCP", "pt": "11. DHCP", "ru": "11. DHCP"},
        "protocols": [
            P("DHCP (IPv4)", "Discover/Offer/Request/Ack lease flow", "Fluxo Discover/Offer/Request/Ack", builder="dhcp"),
            P("DHCPv6", "IPv6 stateful address configuration", "Configuração de endereço IPv6 stateful"),
        ],
    },
    {
        "id": "mgmt",
        "title": {"en": "12. Network Management", "pt": "12. Gerenciamento", "ru": "12. Управление сетью"},
        "protocols": [
            P("SNMPv1", "Basic monitoring, plaintext community string", "Monitoramento básico, community em texto claro", builder="snmp"),
            P("SNMPv2c", "Adds bulk operations, still plaintext", "Adiciona operações em massa, ainda texto claro", builder="snmp"),
            P("SNMPv3", "Adds authentication and encryption", "Adiciona autenticação e criptografia", builder="snmp"),
            P("Syslog", "Sends log messages to a central collector", "Envia mensagens de log para um coletor central"),
            P("NTP", "Synchronizes clocks across the network", "Sincroniza relógios pela rede", builder="ntp"),
            P("SNTP", "Simplified NTP client mode", "Modo cliente NTP simplificado"),
        ],
    },
    {
        "id": "discovery",
        "title": {"en": "13. Discovery / Auto-config", "pt": "13. Descoberta e Configuração", "ru": "13. Обнаружение и настройка"},
        "protocols": [
            P("mDNS", "Multicast DNS for local name resolution", "DNS multicast para resolução local"),
            P("DNS-SD", "Service discovery over DNS/mDNS", "Descoberta de serviços via DNS/mDNS"),
            P("SSDP", "Discovery protocol used by UPnP", "Protocolo de descoberta usado pelo UPnP"),
            P("UPnP", "Automatic device/service discovery & control", "Descoberta e controle automático de dispositivos"),
            P("DHCP", "Automatic IP configuration", "Configuração automática de IP", builder="dhcp"),
            P("LLDP", "Link layer neighbor discovery", "Descoberta de vizinhos na camada de enlace", builder="lldp"),
            P("CDP", "Cisco discovery protocol", "Protocolo de descoberta da Cisco"),
        ],
    },
    {
        "id": "remote",
        "title": {"en": "14. Remote Access", "pt": "14. Acesso Remoto", "ru": "14. Удалённый доступ"},
        "protocols": [
            P("SSH", "Encrypted shell/tunnel/file transfer", "Shell/túnel/transferência criptografados"),
            P("Telnet", "Plaintext remote terminal — avoid using it", "Terminal remoto em texto claro — evite usar"),
            P("RDP", "Microsoft remote desktop protocol", "Protocolo de área de trabalho remota da Microsoft"),
            P("VNC", "Cross-platform remote framebuffer sharing", "Compartilhamento remoto de framebuffer multiplataforma"),
            P("X11", "Unix graphical display protocol", "Protocolo gráfico de display do Unix"),
            P("WinRM", "Windows remote management (SOAP over HTTP)", "Gerenciamento remoto do Windows (SOAP sobre HTTP)"),
        ],
    },
    {
        "id": "sharing",
        "title": {"en": "15. File Sharing", "pt": "15. Compartilhamento de Arquivos", "ru": "15. Общий доступ к файлам"},
        "protocols": [
            P("SMB", "Windows file/print sharing", "Compartilhamento de arquivos/impressão do Windows"),
            P("CIFS", "Older dialect of SMB", "Dialeto mais antigo do SMB"),
            P("NetBIOS", "Legacy name/session service for Windows LANs", "Serviço legado de nome/sessão para LANs Windows"),
            P("NBT", "NetBIOS over TCP/IP", "NetBIOS sobre TCP/IP"),
            P("NFS", "Unix/Linux network file system", "Sistema de arquivos de rede Unix/Linux"),
        ],
    },
    {
        "id": "directory",
        "title": {"en": "16. Directory & Authentication", "pt": "16. Diretórios e Autenticação", "ru": "16. Каталоги и аутентификация"},
        "protocols": [
            P("LDAP", "Queries/updates a directory service", "Consulta/atualiza um serviço de diretório"),
            P("LDAPS", "LDAP wrapped in TLS", "LDAP encapsulado em TLS"),
            P("Kerberos", "Ticket-based network authentication", "Autenticação de rede baseada em tickets"),
            P("RADIUS", "Centralized AAA for network access", "AAA centralizado para acesso à rede", builder="radius"),
            P("TACACS+", "Cisco AAA protocol, separates A/A/A", "Protocolo AAA da Cisco, separa A/A/A"),
            P("Diameter", "AAA protocol used in mobile cores", "Protocolo AAA usado em núcleos móveis"),
        ],
    },
    {
        "id": "voip",
        "title": {"en": "17. VoIP & Multimedia", "pt": "17. VoIP e Multimídia", "ru": "17. VoIP и мультимедиа"},
        "protocols": [
            P("SIP", "Signals/sets up VoIP calls", "Sinaliza/estabelece chamadas VoIP", builder="sip"),
            P("RTP", "Transports audio/video media", "Transporta mídia de áudio/vídeo", builder="rtp"),
            P("RTCP", "Reports RTP session quality stats", "Reporta estatísticas de qualidade da sessão RTP"),
            P("RTSP", "Controls streaming media sessions", "Controla sessões de mídia em streaming"),
            P("SDP", "Describes session media parameters", "Descreve parâmetros de mídia da sessão"),
            P("H.323", "Older ITU multimedia signaling suite", "Suíte de sinalização multimídia ITU mais antiga"),
            P("SRTP", "Encrypted variant of RTP", "Variante criptografada do RTP"),
        ],
    },
    {
        "id": "streaming",
        "title": {"en": "18. Streaming", "pt": "18. Streaming", "ru": "18. Стриминг"},
        "protocols": [
            P("RTMP", "Adobe streaming protocol over TCP", "Protocolo de streaming da Adobe sobre TCP"),
            P("RTSP", "Session control for streaming", "Controle de sessão para streaming"),
            P("RTP", "Media transport", "Transporte de mídia", builder="rtp"),
            P("HLS", "HTTP-based adaptive bitrate streaming", "Streaming adaptativo baseado em HTTP"),
            P("MPEG-DASH", "Standardized adaptive streaming over HTTP", "Streaming adaptativo padronizado sobre HTTP"),
            P("WebRTC", "Real-time peer-to-peer media in the browser", "Mídia peer-to-peer em tempo real no navegador"),
            P("ICE", "NAT traversal candidate negotiation for WebRTC", "Negociação de candidatos NAT para WebRTC"),
            P("STUN", "Discovers public IP/port behind NAT", "Descobre IP/porta pública atrás de NAT"),
            P("TURN", "Relays media when direct P2P fails", "Retransmite mídia quando P2P direto falha"),
            P("DTLS", "Datagram TLS, secures WebRTC data channels", "TLS para datagramas, protege canais WebRTC"),
        ],
    },
    {
        "id": "iot_msg",
        "title": {"en": "19. Messaging / IoT", "pt": "19. Mensageria / IoT", "ru": "19. Обмен сообщениями / IoT"},
        "protocols": [
            P("MQTT", "Lightweight publish/subscribe for IoT", "Publish/subscribe leve para IoT", builder="mqtt"),
            P("MQTT-SN", "MQTT for sensor networks without TCP", "MQTT para redes de sensores sem TCP"),
            P("AMQP", "Enterprise message queuing protocol", "Protocolo empresarial de filas de mensagens"),
            P("CoAP", "REST-like protocol for constrained devices", "Protocolo REST-like para dispositivos restritos", builder="coap"),
            P("DDS", "Data-centric real-time pub/sub middleware", "Middleware pub/sub em tempo real centrado em dados"),
            P("XMPP", "XML-based messaging/presence protocol", "Protocolo de mensagens/presença baseado em XML"),
            P("STOMP", "Simple text-oriented messaging protocol", "Protocolo simples de mensagens orientado a texto"),
        ],
    },
    {
        "id": "k8s",
        "title": {"en": "20. Containers / Kubernetes", "pt": "20. Containers / Kubernetes", "ru": "20. Контейнеры / Kubernetes"},
        "protocols": [
            P("gRPC", "HTTP/2 based RPC framework", "Framework RPC baseado em HTTP/2", builder="http"),
            P("CoreDNS", "Kubernetes internal DNS/service discovery", "DNS interno/descoberta de serviço do Kubernetes"),
            P("CNI", "Container Network Interface plugin spec", "Especificação de plugin de interface de rede de containers"),
            P("Cilium (eBPF)", "eBPF-based networking & security for k8s", "Rede e segurança baseada em eBPF para k8s"),
            P("Calico", "BGP/IPIP based Kubernetes networking", "Rede Kubernetes baseada em BGP/IPIP", builder="bgp"),
            P("Flannel", "Simple overlay networking for Kubernetes", "Rede overlay simples para Kubernetes", builder="vxlan"),
            P("Weave", "Mesh overlay networking for Kubernetes", "Rede overlay em malha para Kubernetes"),
        ],
    },
    {
        "id": "tunneling",
        "title": {"en": "21. Tunneling", "pt": "21. Tunelamento", "ru": "21. Туннелирование"},
        "protocols": [
            P("GRE", "Generic Routing Encapsulation", "Encapsulamento genérico de roteamento", builder="gre"),
            P("IP-in-IP", "IP packet encapsulated in another IP packet", "Pacote IP encapsulado em outro pacote IP"),
            P("VXLAN", "L2 overlay over UDP, common in datacenters", "Overlay L2 sobre UDP, comum em datacenters", builder="vxlan"),
            P("Geneve", "Flexible overlay encapsulation (successor to VXLAN)", "Encapsulamento overlay flexível (sucessor do VXLAN)"),
            P("GTP", "Tunneling protocol for mobile core networks", "Protocolo de tunelamento para núcleos móveis", builder="gtp"),
            P("L2TP", "Tunnels L2 frames, often with IPsec", "Tuneliza quadros L2, geralmente com IPsec"),
            P("PPPoE", "PPP sessions over Ethernet", "Sessões PPP sobre Ethernet", builder="pppoe"),
            P("MPLS", "Label switching instead of full IP lookups", "Comutação por rótulos em vez de lookup IP completo", builder="mpls"),
            P("WireGuard", "Modern encrypted tunneling protocol", "Protocolo de tunelamento criptografado moderno"),
            P("IPsec", "Suite of protocols securing IP traffic", "Conjunto de protocolos que protege tráfego IP"),
        ],
    },
    {
        "id": "mpls",
        "title": {"en": "22. MPLS", "pt": "22. MPLS", "ru": "22. MPLS"},
        "protocols": [
            P("MPLS", "Label switching core technology", "Tecnologia núcleo de comutação por rótulos", builder="mpls"),
            P("LDP", "Distributes MPLS labels between routers", "Distribui rótulos MPLS entre roteadores"),
            P("RSVP-TE", "Traffic-engineered label path signaling", "Sinalização de caminho com engenharia de tráfego"),
            P("Segment Routing", "Source routing using a stack of segments", "Roteamento por origem usando pilha de segmentos"),
            P("SR-MPLS", "Segment Routing over an MPLS data plane", "Segment Routing sobre plano de dados MPLS"),
            P("SRv6", "Segment Routing over an IPv6 data plane", "Segment Routing sobre plano de dados IPv6"),
        ],
    },
    {
        "id": "multicast",
        "title": {"en": "23. Multicast", "pt": "23. Multicast", "ru": "23. Multicast"},
        "protocols": [
            P("IGMP", "Multicast group membership for IPv4", "Associação a grupo multicast para IPv4", builder="igmp"),
            P("MLD", "Multicast listener discovery for IPv6", "Descoberta de ouvintes multicast para IPv6"),
            P("PIM", "Multicast routing protocol family", "Família de protocolos de roteamento multicast"),
            P("PIM-SM", "Sparse mode, explicit join via RP", "Modo esparso, join explícito via RP"),
            P("PIM-DM", "Dense mode, flood-and-prune", "Modo denso, flood-and-prune"),
            P("PIM-SSM", "Source-specific multicast", "Multicast específico de origem"),
        ],
    },
    {
        "id": "iot_wireless",
        "title": {"en": "24. IoT / Wireless", "pt": "24. IoT / Redes sem fio", "ru": "24. IoT / Беспроводные сети"},
        "protocols": [
            P("Zigbee", "Low-power mesh for home automation", "Malha de baixo consumo para automação residencial"),
            P("Z-Wave", "Low-power mesh, common in smart homes", "Malha de baixo consumo, comum em casas inteligentes"),
            P("Thread", "IPv6-based low-power mesh networking", "Rede em malha de baixo consumo baseada em IPv6"),
            P("Matter", "Unified smart home application layer", "Camada de aplicação unificada para casas inteligentes"),
            P("Bluetooth", "Short-range wireless (classic)", "Sem fio de curto alcance (clássico)"),
            P("Bluetooth LE", "Low energy variant of Bluetooth", "Variante de baixa energia do Bluetooth"),
            P("LoRaWAN", "Long range, low power WAN for IoT", "WAN de longo alcance e baixo consumo para IoT"),
            P("NB-IoT", "Narrowband cellular IoT", "IoT celular de banda estreita"),
            P("LTE-M", "LTE variant optimized for IoT", "Variante de LTE otimizada para IoT"),
            P("6LoWPAN", "IPv6 over low-power wireless PANs", "IPv6 sobre redes sem fio de baixo consumo"),
        ],
    },
    {
        "id": "bluetooth",
        "title": {"en": "25. Bluetooth", "pt": "25. Bluetooth", "ru": "25. Bluetooth"},
        "protocols": [
            P("Bluetooth Classic", "Legacy Bluetooth radio + protocols", "Rádio e protocolos Bluetooth legados"),
            P("Bluetooth LE", "Energy efficient Bluetooth mode", "Modo Bluetooth eficiente em energia"),
            P("L2CAP", "Bluetooth logical link control/adaptation", "Controle/adaptação de link lógico Bluetooth"),
            P("RFCOMM", "Serial port emulation over Bluetooth", "Emulação de porta serial sobre Bluetooth"),
            P("ATT", "Attribute protocol used by BLE/GATT", "Protocolo de atributos usado por BLE/GATT"),
            P("GATT", "Generic attribute profile for BLE services", "Perfil de atributos genérico para serviços BLE"),
            P("SMP", "Bluetooth pairing/security manager protocol", "Protocolo de emparelhamento/segurança Bluetooth"),
        ],
    },
    {
        "id": "wifi_sec",
        "title": {"en": "26. Wi-Fi Security", "pt": "26. Segurança Wi-Fi", "ru": "26. Безопасность Wi-Fi"},
        "protocols": [
            P("WPA", "First WEP replacement (TKIP)", "Primeiro substituto do WEP (TKIP)"),
            P("WPA2", "AES-CCMP based Wi-Fi security", "Segurança Wi-Fi baseada em AES-CCMP"),
            P("WPA3", "SAE handshake, stronger Wi-Fi security", "Handshake SAE, segurança Wi-Fi mais forte"),
            P("802.1X", "Port-based access control for Wi-Fi/wired", "Controle de acesso baseado em porta", builder="eapol"),
            P("EAP", "Authentication framework used by 802.1X", "Framework de autenticação usado pelo 802.1X"),
            P("EAP-TLS", "Certificate-based EAP method", "Método EAP baseado em certificado"),
            P("PEAP", "EAP inside a protected TLS tunnel", "EAP dentro de um túnel TLS protegido"),
            P("EAP-TTLS", "EAP with a TLS tunnel, flexible inner auth", "EAP com túnel TLS, autenticação interna flexível"),
        ],
    },
    {
        "id": "storage",
        "title": {"en": "27. Storage Protocols", "pt": "27. Protocolos de Storage", "ru": "27. Протоколы хранения"},
        "protocols": [
            P("iSCSI", "SCSI commands over TCP/IP", "Comandos SCSI sobre TCP/IP"),
            P("Fibre Channel", "Dedicated high-speed storage fabric", "Fabric de armazenamento dedicado de alta velocidade"),
            P("FCoE", "Fibre Channel encapsulated over Ethernet", "Fibre Channel encapsulado sobre Ethernet"),
            P("NVMe-oF", "NVMe commands over a network fabric", "Comandos NVMe sobre uma fabric de rede"),
            P("NFS", "Network file system for Unix/Linux", "Sistema de arquivos de rede para Unix/Linux"),
            P("SMB", "Windows network file system", "Sistema de arquivos de rede do Windows"),
            P("RDMA", "Direct memory access over the network", "Acesso direto à memória pela rede"),
            P("RoCE", "RDMA over Converged Ethernet", "RDMA sobre Ethernet convergente"),
            P("NVMe/TCP", "NVMe-oF transport over plain TCP", "Transporte NVMe-oF sobre TCP simples"),
        ],
    },
    {
        "id": "realtime",
        "title": {"en": "28. Real-Time / Low Latency", "pt": "28. Tempo Real / Baixa Latência", "ru": "28. Реальное время / низкая задержка"},
        "protocols": [
            P("RTP", "Real-time media transport", "Transporte de mídia em tempo real", builder="rtp"),
            P("RTCP", "RTP quality/control reporting", "Relatório de qualidade/controle do RTP"),
            P("QUIC", "Low-latency reliable transport over UDP", "Transporte confiável de baixa latência sobre UDP"),
            P("WebRTC", "Real-time browser communication stack", "Pilha de comunicação em tempo real do navegador"),
            P("RDMA", "Kernel-bypass low latency memory access", "Acesso à memória de baixa latência sem kernel"),
            P("RoCE", "RDMA over converged Ethernet fabrics", "RDMA sobre fabrics Ethernet convergentes"),
            P("InfiniBand", "Very low latency HPC/datacenter fabric", "Fabric de altíssima performance/baixa latência"),
        ],
    },
    {
        "id": "auth",
        "title": {"en": "29. Authentication Protocols", "pt": "29. Protocolos de Autenticação", "ru": "29. Протоколы аутентификации"},
        "protocols": [
            P("PAP", "Plaintext password authentication (legacy)", "Autenticação por senha em texto claro (legado)"),
            P("CHAP", "Challenge-response authentication for PPP", "Autenticação challenge-response para PPP"),
            P("MS-CHAP", "Microsoft variant of CHAP", "Variante Microsoft do CHAP"),
            P("EAP", "Extensible authentication framework", "Framework de autenticação extensível"),
            P("EAP-TLS", "Certificate based EAP", "EAP baseado em certificado"),
            P("RADIUS", "Centralized AAA protocol", "Protocolo AAA centralizado", builder="radius"),
            P("TACACS+", "Cisco AAA protocol", "Protocolo AAA da Cisco"),
            P("Kerberos", "Ticket based mutual authentication", "Autenticação mútua baseada em tickets"),
            P("OAuth 2.0", "Delegated authorization framework", "Framework de autorização delegada"),
            P("OpenID Connect", "Identity layer built on OAuth 2.0", "Camada de identidade sobre OAuth 2.0"),
            P("SAML", "XML-based single sign-on assertions", "Asserções de SSO baseadas em XML"),
        ],
    },
    {
        "id": "firewall",
        "title": {"en": "30. Firewall / Security Inspection", "pt": "30. Firewall / Inspeção de Segurança", "ru": "30. Межсетевой экран / инспекция"},
        "protocols": [
            P("Stateful TCP tracking", "Firewall tracks SYN/SYN-ACK/ACK/FIN state", "Firewall rastreia estado SYN/SYN-ACK/ACK/FIN", builder="tcp_handshake"),
            P("Ethernet -> ARP -> IP -> L4 -> L7 stack inspection", "Deep packet inspection walks every layer", "Inspeção profunda percorre cada camada", builder="ethernet_arp"),
        ],
    },
]


def all_categories():
    return CATEGORIES


def find_category(cat_id):
    for c in CATEGORIES:
        if c["id"] == cat_id:
            return c
    return None
